<?php

namespace ALC\InterBundle\Entity;

/**
 * InterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterRepository extends \Doctrine\ORM\EntityRepository
{
}
