<?php

namespace ALC\InterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    public function findAllOrderedBySite()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ALCInterBundle:Site p ORDER BY p.adresse ASC'
            )
            ->getResult();
    }
}
