<?php

namespace ALC\InterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeinterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeinterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByType()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ALCInterBundle:Typeinter p ORDER BY p.libtyp ASC'
            )
            ->getResult();
    }
}
